[datastax]
client-id = "INSERT_CLIENT_ID_FROM_ASTRA_DATASTAX"
ASTRA_DB_APPLICATION_TOKEN = "INSERT_APP_TOKEN_FROM_ASTRA_DATASTAX"
ASTRA_DB_API_ENDPOINT = "<INSERT_DB_ENDPOINT_FROM_ASTRA_DATASTAX>"
ASTRA_DB_KEYSPACE="<INSERT_KEYSPACE_FROM_ASTRA_DATASTAX>"

[openai]
OPENAI_API_KEY="<INSERT_OPENAI_KEY>"
